[options]
admin_passwd = $pbkdf2-sha512$600000$tBbCGAMgRCjlHONcy7mXEg$/rNLixCYGnkqQ98LqaIf2el7j3GExLsSmVpDnWk3sTtozrRZWK8l6LsKkVJoRnM7T1ES7Tcf9FG6y2.fxVWvwQ
db_host = localhost
db_name = False
list_db = True
db_port = 5432
db_user = odoobiocreto
db_password = odoobiocreto
addons_path = D:\DIEGO\htdocs\Biocretodoo\addons
pg_path = C:\Program Files\PostgreSQL\17\bin
bin_path = C:\Program Files\wkhtmltopdf\bin


# -r odoobiocreto -w odoobiocreto --addons-path=addons -d odoodb
# -c odoo19.conf
# -c odoo19.conf -d odoodb -i base