{
    'name': 'Laboratorio',
    'version': '19.0.1.0.1',
    'category': 'BIOCRETO',
    'summary': 'Control de laboratorio BIOCRETO: probetas, slump, diseños y controles diarios',
    'description': 'Módulo de laboratorio para BIOCRETO: gestión de probetas con rotura programada, ensayos de slump por mixer, cola de asignación de diseños de mezcla y controles diarios de planta.',
    'author': 'BIOCRETO',
    'license': 'LGPL-3',
    'depends': [
        'sale',
        'mrp',
        'fleet',
        'mail',
        'biocreto_base',
        'biocreto_sale_extension',
        'biocreto_sale_contract_state',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/probeta_config_data.xml',
        'views/probeta_config_views.xml',
        'views/probeta_views.xml',
        'views/slump_views.xml',
        'views/cola_disenos_views.xml',
        'views/controles_diarios_views.xml',
        'views/mrp_bom_views.xml',
        'views/sale_order_views.xml',
        'views/menus.xml',
    ],
    'installable': True,
    'application': True,
}
